# Generated by Django 4.2.4 on 2023-09-19 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_address', models.CharField(blank=True, max_length=500, null=True)),
                ('link_name', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
